language: r

# environment variables
env:
  matrix:
    - TARGET=travis
    - TARGET=integration DISPLAY=:99.0

# capturing state, early exit if no integration test is needed
before_install:
  - export RGL_USE_NULL=TRUE
  - tlmgr conf texmf TEXMFHOME $(Rscript -e "cat(file.path(R.home('share'), 'texmf'))")
  - if [ ${TARGET} = integration ]; then
      if ! make integration-need; then
        echo "NOTE:"" Integration test skipped. To enable, create a branch named ${TRAVIS_BRANCH} in ${TRAVIS_REPO_SLUG}-examples.";
        exit 0;
      fi;
    fi
  - "curl -L https://xran.yihui.org/.gitconfig -o ~/.gitconfig"
  - Rscript -e 'update.packages(.libPaths()[1], ask = FALSE)'
  - Rscript -e "if (!require('covr')) install.packages('covr')"

addons:
  apt:
    packages:
    - ghc
    - highlight
    - optipng
    - coffeescript
    - asymptote
    - graphviz
    - scala
    - qpdf
    - texinfo
    - cargo
    - libmagick++-dev
    - libpoppler-cpp-dev
    - libglu1-mesa-dev

repos:
  XRAN: https://xran.yihui.org

cache:
  packages: yes

before_script:
  - Rscript -e "if (!require('webshot')) devtools::install_github('wch/webshot')"

# run tests
script:
  - rm knitr-examples/cache -rf
  - make ${TARGET}

# deploy to xran after integration tests
after_success:
  - "[ $TARGET = travis ] && Rscript -e 'covr::codecov()' || true"
  - export R_PKG="$(basename $TRAVIS_REPO_SLUG)"
  - "[ $TARGET = integration ] && (curl -L https://xran.yihui.org/r-xran | bash)"
