# it is not really c, but there is no R support on Travis CI yet
language: c

# environment variables
env:
  matrix:
    - TARGET=travis
    - TARGET=integration DISPLAY=:99.0
  global:
    secure: AwMvWbAlUxA/SNmXpfm3zL7o5ohB2Qp/qyCrYdLRc8u9v6FBQAVq0NXghsN9NVCUiNO+unSr7qXj9JDcRyx6qj67nEzTM3Pcq1iEUAoWQyhDw9gyTls8wya2K4PG86b2yUAtVFkYBYDakjuTdo786Ili+Dsw4XP0PgtnuozCxuY=

# capturing state, early exit if no integration test is needed
before_install:
  - export PATH=$PATH:$HOME/bin:$HOME/texlive/bin/x86_64-linux
  - if [ ${TARGET} = integration ]; then
      if ! make integration-need; then
        echo "NOTE:"" Integration test skipped. To enable, create a branch named ${TRAVIS_BRANCH} in ${TRAVIS_REPO_SLUG}-examples.";
        exit 0;
      fi;
    fi

# install dependencies
install:
  - sudo apt-add-repository -y "deb http://cran.rstudio.com/bin/linux/ubuntu `lsb_release -cs`/"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo apt-add-repository -y ppa:marutter/c2d4u
  - sudo apt-get update -qq
  - sudo apt-get install -qq r-base-dev r-cran-xml r-cran-rcurl r-cran-rgl r-recommended r-cran-devtools
  - "[ ! -d ~/bin ] && mkdir ~/bin"
  - "wget -q -O - https://github.com/yihui/crandalf/raw/master/inst/scripts/install-texlive | bash"
  - "wget -q -O - https://github.com/yihui/crandalf/raw/master/inst/scripts/install-pandoc | bash"
  - "wget -q -O - http://yihui.name/xran/r-config | bash"
  - Rscript -e "install.packages('stringi')"
  - Rscript -e 'devtools::install_deps(dep = TRUE)'

# run tests
script:
  - make ${TARGET}

# deploy to xran after integration tests
after_success:
  - export R_PKG="$(basename $TRAVIS_REPO_SLUG)"
  - "[ $TARGET = integration ] && (wget -q -O - http://yihui.name/xran/r-xran | bash)"

  # run test coverage only for the travis build
  - "[ $TARGET = travis ] && Rscript -e 'devtools::install_github(\"jimhester/covr\"); covr::coveralls()'"
