language: r
latex: false

# environment variables
env:
  - DISPLAY=:99.0 PATH=$HOME/bin:$PATH RGL_USE_NULL=TRUE

before_install:
  - "curl -L https://xran.yihui.org/.gitconfig -o ~/.gitconfig"
  - Rscript -e 'update.packages(.libPaths()[1], ask = FALSE)'
  - Rscript -e "if (!require('xfun')) install.packages('xfun')"
  - Rscript -e "xfun::pkg_load2('covr', 'tinytex')"
  - Rscript -e "tinytex:::install_prebuilt()"
  - rm TinyTeX.tar.gz

addons:
  apt:
    packages:
    - ghc
    - highlight
    - optipng
    - coffeescript
    - asymptote
    - graphviz
    - scala
    - qpdf
    - texinfo
    - cargo
    - libmagick++-dev
    - libpoppler-cpp-dev
    - libglu1-mesa-dev

repos:
  XRAN: https://xran.yihui.org

cache:
  packages: yes

jobs:
  include:
    - r: oldrel
    - r: release
      # deploy to xran after integration tests
      after_success:
        - Rscript -e 'covr::codecov()'
    - r: release
      name: R release (check knitr-examples)
      script:
        - git clone https://github.com/yihui/knitr-examples.git
        - rm knitr-examples/cache -rf
        - make integration
      # deploy to xran after integration tests
      after_success:
        - export R_PKG="$(basename $TRAVIS_REPO_SLUG)"
        - "curl -L https://xran.yihui.org/r-xran | bash"
    - r: devel
