# it is not really python, but there is no R support on Travis CI yet
language: python

# environment variables
env:
  - R_LIBS_USER=~/R

# install dependencies
install:
  - sudo apt-add-repository -y 'deb http://cran.rstudio.com/bin/linux/ubuntu precise/'
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo apt-add-repository -y ppa:marutter/c2d4u
  - sudo apt-get update
  - sudo apt-get install --no-install-recommends r-base-dev r-cran-xml r-cran-rcurl r-cran-mass r-cran-codetools r-cran-lattice r-cran-matrix r-cran-nlme r-cran-survival r-cran-boot r-cran-cluster r-cran-foreign r-cran-kernsmooth r-cran-rpart r-cran-class r-cran-nnet r-cran-spatial r-cran-mgcv
      qpdf texinfo texlive-latex-recommended texlive-latex-extra lmodern texlive-fonts-recommended texlive-fonts-extra
  - "[ ! -d ~/R ] && mkdir ~/R"
  - R --version
  - R -e '.libPaths(); sessionInfo()'
  - Rscript -e 'install.packages("knitr", dep = TRUE, repos = c("http://rforge.net", "http://cran.rstudio.org"))'

# run tests
script:
  - make install
  - make check
